import { Car } from './types';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    name: 'Mercedes-Benz S-Class',
    brand: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2023,
    price: 150,
    seats: 5,
    fuel: 'Petrol',
    color: 'Silver',
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    isNew: true,
    isLongTripFriendly: true,
  },
  {
    id: '2',
    name: 'BMW 7 Series',
    brand: 'BMW',
    model: '7 Series',
    year: 2022,
    price: 140,
    seats: 5,
    fuel: 'Diesel',
    color: 'Black',
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    isNew: false,
    isLongTripFriendly: true,
  },
  {
    id: '3',
    name: 'Audi R8',
    brand: 'Audi',
    model: 'R8',
    year: 2023,
    price: 300,
    seats: 2,
    fuel: 'Petrol',
    color: 'Red',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1603553329412-449a51093121?auto=format&fit=crop&q=80&w=800',
    rating: 5.0,
    isNew: true,
    isLongTripFriendly: false,
  },
  {
    id: '4',
    name: 'Tesla Model S',
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    price: 120,
    seats: 5,
    fuel: 'Electric',
    color: 'White',
    category: 'Electric',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    isNew: true,
    isLongTripFriendly: true,
  },
  {
    id: '5',
    name: 'Range Rover Vogue',
    brand: 'Land Rover',
    model: 'Range Rover',
    year: 2021,
    price: 180,
    seats: 7,
    fuel: 'Diesel',
    color: 'Grey',
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1606148585254-3b499b3327a8?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    isNew: false,
    isLongTripFriendly: true,
  },
  {
    id: '6',
    name: 'Porsche 911',
    brand: 'Porsche',
    model: '911',
    year: 2023,
    price: 250,
    seats: 2,
    fuel: 'Petrol',
    color: 'Blue',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    isNew: true,
    isLongTripFriendly: false,
  },
  {
    id: '7',
    name: 'Toyota Camry',
    brand: 'Toyota',
    model: 'Camry',
    year: 2022,
    price: 60,
    seats: 5,
    fuel: 'Hybrid',
    color: 'White',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&q=80&w=800',
    rating: 4.5,
    isNew: false,
    isLongTripFriendly: true,
  },
  {
    id: '8',
    name: 'Volkswagen Transporter',
    brand: 'Volkswagen',
    model: 'Transporter',
    year: 2021,
    price: 90,
    seats: 9,
    fuel: 'Diesel',
    color: 'Silver',
    category: 'Van',
    image: 'https://images.unsplash.com/photo-1523983388277-336a66bf9bcd?auto=format&fit=crop&q=80&w=800',
    rating: 4.4,
    isNew: false,
    isLongTripFriendly: true,
  }
];
